### ISSUE TITLE
example for retrieving historical result via API?

### ISSUE THREAD

**Issue by moodonis** [ajcrowe/go-webpagetest#5]
Hi, hope you're well. I've been trying out this excellent wrapper today and am having trouble retrieving a historical result. Debug seems to be of no help, but it is likely I'm using something wrong here.

- I have a file test.go. Its contents are:

```
package main

import (
	"github.com/ajcrowe/go-webpagetest"


)


func main () {

	config := wpt.Config {
	Debug: true,
	}

	client, _ := wpt.NewClient(config)

	id := "180820_QN_10a296745640e020ea2c42074abeb967"

	client.GetResults(id)

	}
```

upon running `go run test.go` i receive `webpagetest: error loading results for test: 180820_QN_10a296745640e020ea2c42074abeb967%`

- However, this test ID clearly exists. It will return a proper json result when you visit: `http://www.webpagetest.org/jsonResult.php?test=180820_QN_10a296745640e020ea2c42074abeb967` 

- Setting Debug: True in the client config for this request seems to do nothing. Debug works great on test submission though. 

Please let me know if you can assist / what I'm doing wrong. Thanks!

**Comment by ajcurated** [comment]
Hi @moodonis I've pushed a fix for this issue was 

* You needed to set a `Host` value in your config.
* I've added a new `NewDefaultConfig()` function to get a sensible default with `Host: https://webpagetest.org` already set #7 
* Fixed a bug with the average results returning a float for the `Connection` field. #8 

Let me know if that works for you
